<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array>
        <string>st</string>
        <string>scl</string>
    </array>
    <key>keyEquivalent</key>
    <string>^~P</string>
    <key>name</key>
    <string>IEC_ST</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>match</key>
            <string>\b(?i:(absolute|abstract|all|and|and_then|array|as|asm|attribute|begin|bindable|case|class|const|constructor|destructor|div|do|do|else|elsif|end|end_if|end_for|end_case|end_while|except|export|exports|external|far|file|finalization|finally|for|forward|goto|if|implementation|import|in|inherited|initialization|interface|interrupt|is|label|library|mod|module|name|near|nil|not|object|of|only|operator|or|or_else|otherwise|packed|pow|private|program|property|protected|public|published|qualified|record|repeat|resident|restricted|segment|set|shl|shr|then|to|try|type|unit|until|uses|value|var|view|virtual|while|with|xor))\b</string>
            <key>name</key>
            <string>keyword.control.IEC_ST</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.prototype.IEC_ST</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.prototype.IEC_ST</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b(?i:(function|procedure))\b\s+(\w+(\.\w+)?)(\(.*?\))?;\s*(?=(?i:attribute|forward|external))</string>
            <key>name</key>
            <string>meta.function.prototype.IEC_ST</string>
        </dict>
        <dict>
            <key>captures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>storage.type.function.IEC_ST</string>
                </dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.function.IEC_ST</string>
                </dict>
            </dict>
            <key>match</key>
            <string>\b(?i:(function|procedure))\b\s+(\w+(\.\w+)?)</string>
            <key>name</key>
            <string>meta.function.IEC_ST</string>
        </dict>
        <dict>
            <key>match</key>
            <string>\b((((D|d|M|m|Q|q|W|w|I|i|R|r|L|l){1,2}%?[0-9a-fA-F]+)|(0(x|X))[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
            <key>name</key>
            <string>constant.numeric.IEC_ST</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>(^[ \t]+)?(?=--)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.whitespace.comment.leading.IEC_ST</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(?!\G)</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>--</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.comment.IEC_ST</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>\n</string>
                    <key>name</key>
                    <string>comment.line.double-dash.IEC_ST.one</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>(^[ \t]+)?(?=//)</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.whitespace.comment.leading.IEC_ST</string>
                </dict>
            </dict>
            <key>end</key>
            <string>(?!\G)</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>//</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.comment.IEC_ST</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>\n</string>
                    <key>name</key>
                    <string>comment.line.double-slash.IEC_ST.two</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>\(\*</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.IEC_ST</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\*\)</string>
            <key>name</key>
            <string>comment.block.IEC_ST.one</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>\{</string>
            <key>captures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.comment.IEC_ST</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>name</key>
            <string>comment.block.IEC_ST.two</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.IEC_ST</string>
                </dict>
            </dict>
            <key>comment</key>
            <string>Double quoted strings are an extension and (generally) support C-style escape sequences.</string>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.IEC_ST</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.IEC_ST</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\.</string>
                    <key>name</key>
                    <string>constant.character.escape.IEC_ST</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>applyEndPatternLast</key>
            <integer>1</integer>
            <key>begin</key>
            <string>'</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.IEC_ST</string>
                </dict>
            </dict>
            <key>end</key>
            <string>'</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.IEC_ST</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.single.IEC_ST</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>''</string>
                    <key>name</key>
                    <string>constant.character.escape.apostrophe.IEC_ST</string>
                </dict>
            </array>
        </dict>
    </array>
    <key>scopeName</key>
    <string>source.IEC_ST</string>
    <key>uuid</key>
    <string>B3DBEADD-1E6C-47BC-B0F4-CE0E23726FA1</string>
</dict>
</plist>